import LocalizedStrings from 'react-native-localization';

const localization = new LocalizedStrings({
  en: {
    aboutTitle: 'About Us',
    aboutContent: 'Learn about Community Tax Centers and what we do by clicking here',
    missionTitle: 'Our Mission',
    missionContent: 'Dallas Community Tax Centers offer free tax preparation to individuals and families that make less than $58,000 a year',
    storyTitle: 'Our Story',
    storyContent: 'The Dallas Community Tax Centers is a Foundation Communities program that returns millions of dollars to the local economy by helping low to moderate income families take better control of their finances. During the tax season, IRS-certified volunteers offer free tax help to individuals and families who earn less than $60,000 a year. Additionally, CTC is helping develop a scalable model for financial education and coaching that can connect low-income individuals and families with helpful benefits and community resources - and teach them the management skills to keep more of the money they earn.',
    checklistTitle: 'Item Checklist',
    checklistContent: 'Make sure you bring everything needed to your appointment by downloading this checklist or visiting the in-app checklist',
    basicInfo: 'Basic Info',
    ssCard: 'Social Security Cards or ITIN Letters for everyone on the tax return',
    idCard: 'Your photo ID',
    bankInfo: 'Bank Information (routing and account numbers for direct deposit)',
    prevTaxReturn: 'Last year\'s tax return',
    docsReceived: 'Documents Received',
    w2: 'Form W-2s - Wage and Tax Statement',
    form1099: 'Form 1099s - Interest Income (1099-INT), Unemployed Compensation (1099-G), Miscellaneous Income (1099-MISC), Divided Income (1099-DIV), Retirement Plan Distribution (1099-R) & Cancellation of Debt (1099-C)',
    form1095A: 'Form 1095-A - Health Insurance Marketplace Statement',
    form1095B: 'Form 1095-B - Health coverage form from insurance company',
    form1095C: 'Form 1095-C - Health coverage form from employer',
    exemption: 'Health Insurance Marketplace exemption certificate',
    form1098T: 'Form 1098-T - Tuition Statement - along with student account summary',
    form1098E: 'Form 1098-E - Student Loan Interest Statement',
    form1099SSA: 'Form 1099-SSA - Social Security Benefit Statement',
    form1098: 'FOR HOMEOWNERS: Form 1098 - Mortgage Interest Statement',
    realEstateTax: 'FOR HOMEOWNERS: Receipt showing real estate taxes paid',
    w2G: 'Form W-2G - Certain Gambling Winnings',
    personalRecs: 'Personal Records',
    careExpenses: 'Child and dependent care expenses',
    educationExpenses: 'Education expenses - detailed student account summary',
    medicalExpenses: 'Medical expenses',
    charitableContr: 'Charitable contributions',
    retirementContr: 'Retirement contributions',
    energyReceipt: 'FOR HOMEOWNERS: Receipts for energy saving improvements on your home',
    selfEmployed: 'If You Are Self-Employed',
    businessExpenses: 'Record of business expenses, business income, and Forms 1099-MISC',
    businessIncome: 'Record of business income',
    form1099Misc: 'Forms 1099-MISC',
    refundTitle: 'Where\'s My Refund?',
    refundContent: 'Link to IRS Where\'s My Refund page',
    facebookTitle: 'Find Us On Facebook',
    facebookContent: 'Visit our Facebook page to find out more',
    openMaps: 'Open in Google Maps',
    getWait: 'Get Estimated Wait Time',
    waitContent: 'Wait Time: ',
    updatedContent: 'Last Updated: ',
    enterCred: 'Enter Credentials',
    usernameHint: 'Username',
    passwordHint: 'Password',
    loginPrompt: 'Login',
    editLoc: 'Choose a location to edit',
    selectLoc: 'Select a location',
    enterWait: 'Enter wait time for the specified location',
    waitHint: 'Wait Time',
    timePrompt: 'Update Time',
    locNameHint: 'Location Name',
    locAddHint: 'Location Address',
    locPrompt: 'Update Location Info',
    addPrompt: 'Add New Location',
    deletePrompt: 'Delete Location',
    locationAccessTitle: 'Foundation Communities Location Access',
    locationAccessMessage: 'Location needed to determine the distance between our centers and you',
    saveTimeTitle: 'Want to Save time?',
    saveTimeContent: 'Please fill out and PRINT Intake Sheet BEFORE arriving to one of the tax centers.',
  },
  es: {
    aboutTitle: ' Acerca de Nosotros’',
    aboutContent: 'Aprenda sobre los Centros Comunitarios de Impuestos y lo que hacemos haciendo clic aquí',
    missionTitle: 'Nuestra Misión',
    missionContent: 'Dallas Community Tax Centers  ofrece preparación de impuestos gratuita a individuos y familias que ganan menos de $58,000 al año',
    storyTitle: 'Nuestra Historia',
    storyContent: 'Dallas Community Tax Centers es un programa de Foundation Communities que devuelve millones de dólares a la economía local al ayudar a las familias de ingresos bajos a moderados a tener un mejor control de sus finanzas. Durante la temporada de impuestos, nuestros voluntarios certificados por el IRS ofrecen ayuda gratuita a las personas y familias que ganan menos de $ 60,000 al año. Además, CTC está ayudando a desarrollar un modelo escalable para la educación financiera y el entrenamiento que puede conectar a individuos y familias de bajos ingresos con beneficios útiles y recursos comunitarios, y enseñarles las habilidades para conservar más del dinero que ganan.',
    checklistTitle: 'Lista de Verificación',
    checklistContent: 'Asegúrese de llevar todo lo necesario a su cita descargando esta lista de verificación o visitando la lista de verificación en la aplicación',
    basicInfo: 'Información Básica',
    ssCard: 'Tarjetas de Seguridad Social o cartas ITIN para todos en la declaración de impuestos',
    idCard: 'Prueba de identidad (con fotografía)',
    bankInfo: 'Número de tránsito bancario y número de cuenta para depósito directo tal como un cheque en blanco',
    prevTaxReturn: 'Declaración de impuestos del año pasado',
    docsReceived: 'Documentos recibidos',
    w2: 'Formulario W-2s - Declaración de salarios e impuestos',
    form1099: 'Formulario 1099: Ingresos por Intereses (1099-INT), Compensación por Desempleo (1099-G), Ingresos por Servicios Como Contratista Independiente (1099-MISC), Ingresos Dividendos (1099-DIV), Distribución del Plan de Jubilación (1099-R) y Cancelación de la Deuda (1099 -C)',
    form1095A: 'Formulario 1095-A - Declaración del Mercado de Seguros Médicos',
    form1095B: 'Formulario 1095-B – Cobertura de Salud',
    form1095C: 'Formulario 1095-C - Oferta de Seguro de Salud y Seguro de Cobertura Proporcionados por el Empleador',
    exemption: 'Certificado de Exención del Mercado de Seguros de Salud',
    form1098T: 'Formulario 1098-T - Declaración de Matrícula - Junto con el Resumen de Cuenta de el Estudiante',
    form1098E: 'Formulario 1098-E - Declaración de interés de préstamo estudiantil',
    form1099SSA: 'Formulario 1099-SSA - Declaración de beneficios del Seguro Social',
    form1098: 'PARA PROPIETARIOS: Formulario 1098 - Declaración de Intereses Hipotecarios',
    realEstateTax: 'PARA PROPIETARIOS: Recibo de impuestos de bienes raíces pagados',
    w2G: 'Formulario W-2G - Ciertas ganancias de Apuestas',
    personalRecs: 'Archivos Personales',
    careExpenses: 'Gastos de Cuidado de Menores y Dependientes',
    educationExpenses: 'Gastos de educación - Resumen de Cuenta de el Estudiante',
    medicalExpenses: 'Gastos Médicos',
    charitableContr: 'Contribuciones Caritativas',
    retirementContr: 'Contribuciones de jubilación',
    energyReceipt: 'PARA PROPIETARIOS: Recibos de Mejoramiento para el Ahorro de Energía en su Hogar',
    selfEmployed: 'Si Trabaja por Cuenta Propia',
    businessExpenses: 'Registro de los gastos del negocio, los ingresos del negocio y todos los  formularios  1099-MISC',
    businessIncome: 'Registro de ingresos del negocio',
    form1099Misc: 'Formulario 1099-MISC',
    refundTitle: '¿Dónde está mi reembolso?',
    refundContent: 'Enlace a la pagina de ¿Dónde está mi reembolso?',
    facebookTitle: 'Encuentranos en Facebook',
    facebookContent: 'Visite Nuestra Página de Facebook para Obtener Más Información',
    openMaps: 'Abrir en Google Maps',
    getWait: 'Obtener Tiempo de Espera Estimado',
    waitContent: 'Tiempo de Espera: ',
    updatedContent: 'Última Actualización: ',
    enterCred: 'Ingresar Credenciales',
    usernameHint: 'Nombre de Usuario',
    passwordHint: 'Contraseña',
    loginPrompt: 'Iniciar Sesión',
    editLoc: 'Elija una Ubicación para Editar',
    selectLoc: 'Selecciona una ubicación',
    enterWait: 'Elija Tiempo de Espera Para Ubicación Específica',
    waitHint: 'Tiempo de Espera',
    timePrompt: 'Tiempo de actualizacion',
    locNameHint: 'Nombre de Ubicación',
    locAddHint: 'Dirección de Ubicación ',
    locPrompt: 'Actualizar Informacion de Ubicación',
    addPrompt: 'Agregar Nueva Ubicación',
    deletePrompt: 'Eliminar Ubicación',
    locationAccessTitle: 'Acceso a la ubicación de comunidades fundacionales',
    locationAccessMessage: 'Ubicación necesaria para determinar la distancia entre nuestros centros y usted',
    saveTimeTitle: '¿Quiere ahorrar tiempo?',
    saveTimeContent: 'Complete e IMPRIMA la hoja de admisión ANTES de llegar a uno de los centros de impuestos.',
  },
});

export default localization;
